(()=>{"use strict";
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const rupiah=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
async function g6Session(){return window.kwSupabase?.auth?.getSession?((await window.kwSupabase.auth.getSession()).data?.session||null):null}
async function g6Api(method="GET",body){
 const s=await g6Session();if(!s)throw new Error("Silakan masuk terlebih dahulu.");
 const r=await fetch("/api/loyalty",{method,headers:{Authorization:"Bearer "+s.access_token,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined,cache:"no-store"});
 const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Gagal memproses loyalty.");return d;
}
function tierLabel(t){return ({member:"Member",silver:"Silver",gold:"Gold",platinum:"Platinum"}[t]||"Member")}
async function loadG6Loyalty(){
 const root=document.getElementById("g6LoyaltyRoot");if(!root)return;
 root.innerHTML='<div class="account-empty">Memuat Koin MarketKita...</div>';
 try{
  const d=await g6Api();const s=d.summary||{};const tx=Array.isArray(s.recent_transactions)?s.recent_transactions:[];
  root.innerHTML='<div class="g6-loyalty-hero"><div><span class="g6-kicker">MARKETKITA REWARDS</span><h4>'+Number(s.points_balance||0).toLocaleString("id-ID")+' Koin</h4><p>Setiap Rp1.000 nilai produk pada pesanan yang selesai = 1 koin.</p></div><b>'+esc(tierLabel(s.tier))+'</b></div>'+
   '<div class="g6-loyalty-grid"><div><strong>'+Number(s.lifetime_earned||0).toLocaleString("id-ID")+'</strong><span>Total diperoleh</span></div><div><strong>'+Number(s.lifetime_redeemed||0).toLocaleString("id-ID")+'</strong><span>Total ditukar</span></div><div><strong>Rp1</strong><span>Nilai 1 koin</span></div></div>'+
   '<div class="g6-redeem"><div><strong>Tukar Koin menjadi Voucher</strong><small>Minimal 1.000 koin dan kelipatan 1.000. Voucher berlaku 30 hari.</small></div><div class="g6-redeem-row"><input id="g6RedeemPoints" type="number" min="1000" step="1000" value="'+(Number(s.points_balance||0)>=1000?1000:1000)+'"><button type="button" onclick="g6Redeem()">Tukar Koin</button></div><div id="g6RedeemMsg"></div></div>'+
   '<div class="g6-history"><h4>Aktivitas Koin</h4>'+(tx.length?tx.map(x=>'<div class="g6-tx"><span><strong>'+esc(x.description||"Aktivitas")+'</strong><small>'+new Date(x.created_at).toLocaleString("id-ID")+'</small></span><b class="'+(Number(x.points)<0?"out":"in")+'">'+(Number(x.points)>0?"+":"")+Number(x.points).toLocaleString("id-ID")+'</b></div>').join(""):'<div class="account-empty">Belum ada aktivitas koin.</div>')+'</div>';
 }catch(e){root.innerHTML='<div class="account-empty">Gagal memuat Koin MarketKita: '+esc(e.message||"Terjadi kesalahan.")+'</div>'}
}
window.g6Redeem=async()=>{const input=document.getElementById("g6RedeemPoints"),msg=document.getElementById("g6RedeemMsg"),btn=document.querySelector(".g6-redeem-row button");const points=Math.trunc(Number(input?.value||0));if(!Number.isFinite(points)||points<1000||points%1000!==0){if(msg)msg.textContent="Masukkan koin minimal 1.000 dan kelipatan 1.000.";return}if(btn)btn.disabled=true;if(msg)msg.textContent="Menukar koin...";
 try{const d=await g6Api("POST",{points});if(msg)msg.innerHTML='Berhasil. Voucher <strong>'+esc(d.code||"")+'</strong> senilai '+rupiah(d.discount_amount||points)+' sudah masuk ke Voucher Saya.';await loadG6Loyalty();window.loadVouchers?.();}catch(e){if(msg)msg.textContent=e.message||"Gagal menukar koin."}finally{if(btn)btn.disabled=false}};
window.loadG6Loyalty=loadG6Loyalty;
const style=document.createElement("style");style.textContent='.g6-loyalty-hero{display:flex;justify-content:space-between;gap:20px;padding:25px;border-radius:20px;background:#171817;color:#fff;margin-bottom:14px}.g6-loyalty-hero h4{font-size:30px;margin:8px 0 5px}.g6-loyalty-hero p{margin:0;color:#c9c5bd;font-size:12px}.g6-kicker{font-size:9px;letter-spacing:.15em;font-weight:900;color:#bdb7ae}.g6-loyalty-hero>b{height:max-content;border:1px solid #ffffff40;border-radius:999px;padding:9px 13px;font-size:11px}.g6-loyalty-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:14px}.g6-loyalty-grid>div,.g6-redeem,.g6-history{background:#fffdf9;border:1px solid #e4ded5;border-radius:16px;padding:17px}.g6-loyalty-grid strong{display:block;font-size:20px}.g6-loyalty-grid span,.g6-redeem small,.g6-tx small{display:block;color:#858078;font-size:10px;margin-top:4px}.g6-redeem{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:14px}.g6-redeem-row{display:flex;gap:7px}.g6-redeem-row input{width:130px;height:40px;border:1px solid #d8d2c8;border-radius:9px;padding:0 10px}.g6-redeem-row button{height:40px;border:0;border-radius:9px;background:#171817;color:#fff;padding:0 14px;font-weight:800}.g6-redeem-row button:disabled{opacity:.5}.g6-redeem #g6RedeemMsg{font-size:10px;color:#6c6860;margin-top:6px}.g6-history h4{margin:0 0 12px}.g6-tx{display:flex;justify-content:space-between;gap:15px;padding:12px 0;border-top:1px solid #eee9e1}.g6-tx strong{display:block;font-size:12px}.g6-tx b.in{color:#217a45}.g6-tx b.out{color:#b3261e}@media(max-width:650px){.g6-loyalty-hero,.g6-redeem{display:block}.g6-loyalty-hero>b{display:inline-block;margin-top:12px}.g6-loyalty-grid{grid-template-columns:1fr}.g6-redeem-row{margin-top:12px}.g6-redeem-row input{flex:1;width:auto}}';document.head.appendChild(style);
document.addEventListener("DOMContentLoaded",()=>setTimeout(loadG6Loyalty,1000));
const original=window.showAccountSection;window.showAccountSection=function(section){if(typeof original==="function")original(section);if(section==="coins")setTimeout(loadG6Loyalty,0)};
})();