(()=>{"use strict";
const SW="/sw.js"; const INSTALL_KEY="marketkita_pwa_install_dismissed_v1"; let deferredInstall=null;
function safeTrack(name,metadata={}){try{window.marketKitaTrack?.(name,{metadata})}catch{}}
function banner(text,type="info"){let el=document.getElementById("mkPwaBanner");if(!el){el=document.createElement("div");el.id="mkPwaBanner";el.style.cssText="position:fixed;left:14px;right:14px;bottom:14px;z-index:9998;background:#171817;color:#fff;border-radius:14px;padding:11px 14px;box-shadow:0 14px 40px #0003;font-size:12px;display:flex;align-items:center;justify-content:space-between;gap:10px";document.body.appendChild(el)}el.innerHTML="<span>"+String(text).replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]))+"</span><button id=\"mkPwaBannerClose\" style=\"border:0;background:#fff;color:#171817;border-radius:8px;padding:6px 9px;font-weight:800\">×</button>";el.querySelector("button").onclick=()=>el.remove();if(type==="offline")el.style.background="#7a3428"}
function installButton(){if(document.getElementById("mkPwaInstall"))return;const b=document.createElement("button");b.id="mkPwaInstall";b.type="button";b.textContent="Install MarketKita";b.style.cssText="position:fixed;right:16px;bottom:82px;z-index:9997;border:0;background:#171817;color:#fff;border-radius:999px;padding:11px 15px;font-size:12px;font-weight:850;box-shadow:0 12px 32px #0003;display:none";b.onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();const choice=await deferredInstall.userChoice;safeTrack("pwa_install_prompt",{metadata:{outcome:choice?.outcome||"unknown"}});deferredInstall=null;b.remove()};document.body.appendChild(b);return b}
async function registerSW(){if(!("serviceWorker" in navigator))return null;try{const reg=await navigator.serviceWorker.register(SW,{scope:"/",updateViaCache:"none"});reg.addEventListener("updatefound",()=>safeTrack("pwa_update_found"));return reg}catch(e){safeTrack("pwa_registration_error",{metadata:{message:String(e?.message||e)}});return null}}
function setupNetwork(){const update=()=>{if(navigator.onLine){document.getElementById("mkPwaOffline")?.remove();}else{if(!document.getElementById("mkPwaOffline")){const el=document.createElement("div");el.id="mkPwaOffline";el.textContent="Offline — MarketKita akan mencoba menggunakan data yang tersimpan.";el.style.cssText="position:fixed;top:0;left:0;right:0;z-index:10000;background:#7a3428;color:#fff;text-align:center;padding:7px 10px;font-size:11px;font-weight:800";document.body.appendChild(el)}}};window.addEventListener("online",update);window.addEventListener("offline",update);update()}
async function setupInstall(){const b=installButton();window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;b.style.display="block";safeTrack("pwa_install_available")});window.addEventListener("appinstalled",()=>{deferredInstall=null;b?.remove();safeTrack("pwa_installed")});if(window.matchMedia?.("(display-mode: standalone)").matches||navigator.standalone===true){safeTrack("pwa_launched_standalone")}}
async function setupNotifications(){if(!("Notification" in window)||!("serviceWorker" in navigator))return;window.marketKitaEnableNotifications=async()=>{try{const permission=await Notification.requestPermission();safeTrack("notification_permission",{metadata:{permission}});if(permission!=="granted")return false;const reg=await navigator.serviceWorker.ready;await reg.showNotification("MarketKita",{body:"Notifikasi MarketKita aktif di perangkat ini.",icon:"/icons/marketkita-pwa.svg",badge:"/icons/marketkita-pwa.svg",tag:"marketkita-notification-test"});return true}catch(e){safeTrack("notification_error",{metadata:{message:String(e?.message||e)}});return false}}}
document.addEventListener("DOMContentLoaded",async()=>{await registerSW();setupNetwork();setupInstall();setupNotifications();if(location.search.includes("source=pwa"))safeTrack("pwa_launch");});
})();