function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
const base=v=>String(v||"").trim().replace(/\/+$/,"");
async function req(url,key,path,options={}){const r=await fetch(url+path,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d={raw:t}}if(!r.ok){const e=new Error(d?.message||d?.details||d?.hint||d?.error||`Supabase HTTP ${r.status}`);e.status=r.status;throw e}return d}
async function authUser(request,url,anon){const h=request.headers.get("Authorization")||"";if(!/^bearer\s+/i.test(h))return null;const token=h.replace(/^bearer\s+/i,"").trim();if(!token)return null;const r=await fetch(url+"/auth/v1/user",{headers:{apikey:anon,Authorization:"Bearer "+token}});return r.ok?r.json():null}
function midtransAuth(key){return "Basic "+btoa(key+":")}
async function admin(request,env){const url=base(env.SUPABASE_URL),service=String(env.SUPABASE_SERVICE_ROLE_KEY||""),anon=String(env.SUPABASE_ANON_KEY||"");const u=await authUser(request,url,anon);if(!u?.id)return {error:"Login admin diperlukan.",status:401};const p=await req(url,service,`/rest/v1/profiles?select=id,role&id=eq.${encodeURIComponent(u.id)}&limit=1`);if(p?.[0]?.role!=="admin")return {error:"Akses ditolak.",status:403};return {url,service,anon,user:u}}
export async function onRequestGet({env,request}){try{const a=await admin(request,env);if(a.error)return json({error:a.error},a.status);const q=new URL(request.url).searchParams;let path="/rest/v1/return_requests?select=*&order=created_at.desc&limit=200";if(q.get("status"))path+="&status=eq."+encodeURIComponent(q.get("status"));const rows=await req(a.url,a.service,path);return json({requests:Array.isArray(rows)?rows:[]})}catch(e){return json({error:e.message||"Gagal mengambil retur."},500)}}
export async function onRequestPost({env,request}){try{
 const a=await admin(request,env);if(a.error)return json({error:a.error},a.status);const body=await request.json().catch(()=>({}));const id=String(body.return_id||"").trim(),action=String(body.action||"").trim();if(!id||!action)return json({error:"return_id dan action wajib diisi."},400);
 const rows=await req(a.url,a.service,`/rest/v1/return_requests?select=*&id=eq.${encodeURIComponent(id)}&limit=1`);if(!rows?.length)return json({error:"Pengajuan retur tidak ditemukan."},404);const r=rows[0];
 const map={approve:"approved",reject:"rejected",shipping_back:"shipping_back",receive:"received",cancel:"cancelled"};
 if(map[action]){const result=await req(a.url,a.service,"/rest/v1/rpc/seller_update_return",{method:"POST",body:JSON.stringify({p_return_id:id,p_status:map[action],p_tracking_number:body.tracking_number||null,p_note:body.note||null})});return json({ok:true,return_request:Array.isArray(result)?result[0]:result})}
 if(action!=="resolve")return json({error:"Action tidak dikenal."},400);
 if(r.status!=="received")return json({error:"Retur harus berstatus received sebelum diselesaikan."},400);
 if(r.type==="replacement"){const result=await req(a.url,a.service,"/rest/v1/rpc/seller_update_return",{method:"POST",body:JSON.stringify({p_return_id:id,p_status:"resolved",p_tracking_number:body.tracking_number||null,p_note:body.note||"Replacement diselesaikan oleh admin."})});return json({ok:true,type:"replacement",return_request:Array.isArray(result)?result[0]:result})}
 const midKey=String(env.MIDTRANS_SERVER_KEY||"");if(!midKey)return json({error:"MIDTRANS_SERVER_KEY belum dikonfigurasi."},500);const amount=Math.max(0,Number(r.approved_amount||r.requested_amount||0));if(!amount)return json({error:"Nominal refund tidak valid."},400);
 const orders=await req(a.url,a.service,`/rest/v1/orders?select=id,midtrans_order_id,midtrans_transaction_id,payment_status,total&id=eq.${encodeURIComponent(r.order_id)}&limit=1`);const order=orders?.[0];if(!order)return json({error:"Order tidak ditemukan."},404);if(order.payment_status!=="paid")return json({error:"Order belum berstatus paid."},400);
 let rr=r.refund_request_id?await req(a.url,a.service,`/rest/v1/refund_requests?select=*&id=eq.${encodeURIComponent(r.refund_request_id)}&limit=1`):[];let refund=rr?.[0]||null;
 if(refund&&["pending_confirmation","succeeded"].includes(String(refund.status)))return json({ok:true,type:"return_refund",status:refund.status,refund_key:refund.refund_key,already_requested:true});
 const refundKey="MK-RETURN-"+crypto.randomUUID().replace(/-/g,"");
 if(!refund){const inserted=await req(a.url,a.service,"/rest/v1/refund_requests?select=*",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({dispute_id:null,return_request_id:r.id,order_id:r.order_id,buyer_id:r.buyer_id,admin_id:a.user.id,refund_key:refundKey,amount,reason:"Return & Refund MarketKita: "+String(r.reason||"").slice(0,180),status:"requested"})});refund=inserted?.[0];if(!refund)throw new Error("Refund request gagal dibuat.");await req(a.url,a.service,`/rest/v1/return_requests?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({refund_request_id:refund.id,approved_amount:amount,updated_at:new Date().toISOString()})})}
 const midtransId=String(order.midtrans_order_id||order.midtrans_transaction_id||"").trim();if(!midtransId)throw new Error("Order belum memiliki ID transaksi Midtrans.");const production=String(env.MIDTRANS_IS_PRODUCTION||"false").toLowerCase()==="true";const endpoint=(production?"https://api.midtrans.com/v2/":"https://api.sandbox.midtrans.com/v2/")+encodeURIComponent(midtransId)+"/refund";
 const resp=await fetch(endpoint,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json",Authorization:midtransAuth(midKey)},body:JSON.stringify({refund_key:refund.refund_key||refundKey,amount,reason:"Return & Refund MarketKita"})});const tx=await resp.text();let data=null;try{data=tx?JSON.parse(tx):null}catch{data={raw:tx}};
 if(!resp.ok){await req(a.url,a.service,"/rest/v1/rpc/service_update_refund_request",{method:"POST",body:JSON.stringify({p_refund_key:refund.refund_key||refundKey,p_status:"failed",p_status_code:String(data?.status_code||resp.status),p_status_message:String(data?.status_message||data?.message||"Midtrans menolak refund."),p_raw_response:data||{},p_error_message:String(data?.status_message||data?.message||"Midtrans menolak refund.")})});return json({error:data?.status_message||data?.message||"Midtrans menolak refund."},502)}
 await req(a.url,a.service,"/rest/v1/rpc/service_update_refund_request",{method:"POST",body:JSON.stringify({p_refund_key:refund.refund_key||refundKey,p_status:"pending_confirmation",p_status_code:String(data?.status_code||"200"),p_status_message:String(data?.status_message||"Refund diterima Midtrans."),p_refund_amount:Number(data?.refund_amount||amount),p_midtrans_transaction_id:String(data?.transaction_id||order.midtrans_transaction_id||"")||null,p_raw_response:data||{},p_error_message:null})});
 const resolved=await req(a.url,a.service,"/rest/v1/rpc/seller_update_return",{method:"POST",body:JSON.stringify({p_return_id:id,p_status:"resolved",p_tracking_number:body.tracking_number||null,p_note:body.note||"Refund diterima Midtrans; menunggu konfirmasi provider."})});
 return json({ok:true,type:"return_refund",status:"pending_confirmation",refund_key:refund.refund_key||refundKey,return_request:Array.isArray(resolved)?resolved[0]:resolved});
}catch(e){console.error("admin return:",e);return json({error:e.message||"Gagal memproses retur."},500)}}
