function json(d,s=200){return new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
const clean=v=>String(v??"").trim();
async function auth(ctx){const base=clean(ctx.env.SUPABASE_URL).replace(/\/+$/,""),key=clean(ctx.env.SUPABASE_ANON_KEY),h=ctx.request.headers.get("Authorization")||"";if(!base||!key||!/^Bearer\s+/i.test(h))return null;const r=await fetch(base+"/auth/v1/user",{headers:{apikey:key,Authorization:h}});return r.ok?r.json().catch(()=>null):null}
async function svc(ctx,path,opt={}){const base=clean(ctx.env.SUPABASE_URL).replace(/\/+$/,""),key=clean(ctx.env.SUPABASE_SERVICE_ROLE_KEY);if(!base||!key)throw Error("SUPABASE_SERVER_CONFIG_MISSING");const r=await fetch(base+path,{...opt,headers:{apikey:key,Authorization:"Bearer "+key,"Content-Type":"application/json",...(opt.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d={raw:t}}if(!r.ok)throw Error(d?.message||d?.details||d?.hint||d?.error||("Supabase HTTP "+r.status));return d}
async function rpc(ctx,name,args,authHeader){const base=clean(ctx.env.SUPABASE_URL).replace(/\/+$/,""),key=clean(ctx.env.SUPABASE_ANON_KEY);const r=await fetch(base+"/rest/v1/rpc/"+name,{method:"POST",headers:{apikey:key,Authorization:authHeader,"Content-Type":"application/json"},body:JSON.stringify(args)});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d={raw:t}}if(!r.ok)throw Error(d?.message||d?.details||d?.hint||d?.error||("RPC HTTP "+r.status));return d}
async function profile(ctx,id){const a=await svc(ctx,"/rest/v1/profiles?select=id,role& id=eq."+encodeURIComponent(id)+"&limit=1".replace(" ",""));return a?.[0]||null}
const validTarget=t=>["user","store","product","order","review","chat"].includes(t);
export async function onRequestGet(ctx){try{const u=await auth(ctx);if(!u?.id)return json({error:"LOGIN_REQUIRED"},401);const p=await profile(ctx,u.id),role=clean(p?.role).toLowerCase();const url=new URL(ctx.request.url),admin=url.searchParams.get("admin")==="1";
if(admin&&role!=="admin")return json({error:"ADMIN_REQUIRED"},403);
if(admin){const status=url.searchParams.get("status");const q=status?"&status=eq."+encodeURIComponent(status):"";const reports=await svc(ctx,"/rest/v1/safety_reports?select=id,reporter_id,target_type,target_id,reason,description,status,priority,resolution_note,resolved_by,resolved_at,created_at,updated_at&order=created_at.desc&limit=200"+q);return json({ok:true,reports:reports||[]})}
const [reports,blocks]=await Promise.all([svc(ctx,"/rest/v1/safety_reports?select=id,target_type,target_id,reason,description,status,priority,resolution_note,resolved_at,created_at&reporter_id=eq."+encodeURIComponent(u.id)+"&order=created_at.desc&limit=100"),svc(ctx,"/rest/v1/user_blocks?select=id,blocked_id,created_at&blocker_id=eq."+encodeURIComponent(u.id)+"&order=created_at.desc&limit=100")]);return json({ok:true,reports:reports||[],blocks:blocks||[]})}catch(e){return json({error:e.message||"SAFETY_GET_FAILED"},500)}}
export async function onRequestPost(ctx){try{const u=await auth(ctx);if(!u?.id)return json({error:"LOGIN_REQUIRED"},401);if(Number(ctx.request.headers.get("Content-Length")||0)>16384)return json({error:"PAYLOAD_TOO_LARGE"},413);const b=await ctx.request.json().catch(()=>null);if(!b||typeof b!=="object"||Array.isArray(b))return json({error:"INVALID_PAYLOAD"},400);const h=ctx.request.headers.get("Authorization")||"",action=clean(b.action).toLowerCase();
if(action==="report"){const targetType=clean(b.target_type),targetId=clean(b.target_id);if(!validTarget(targetType)||!/^[0-9a-f-]{36}$/i.test(targetId))return json({error:"TARGET_INVALID"},400);const id=await rpc(ctx,"submit_safety_report",{p_target_type:targetType,p_target_id:targetId,p_reason:clean(b.reason),p_description:clean(b.description)},h);return json({ok:true,report_id:id})}
if(action==="block"||action==="unblock"){const id=clean(b.user_id);if(!/^[0-9a-f-]{36}$/i.test(id))return json({error:"USER_ID_INVALID"},400);const result=await rpc(ctx,"toggle_user_block",{p_blocked_id:id,p_block:action==="block"},h);return json({ok:true,result})}
if(action==="moderate"){const p=await profile(ctx,u.id);if(clean(p?.role).toLowerCase()!=="admin")return json({error:"ADMIN_REQUIRED"},403);const id=clean(b.report_id);if(!/^[0-9a-f-]{36}$/i.test(id))return json({error:"REPORT_ID_INVALID"},400);const result=await rpc(ctx,"admin_moderate_safety_report",{p_report_id:id,p_status:clean(b.status),p_action:clean(b.moderation_action),p_note:clean(b.note)||null},h);return json({ok:true,result})}
return json({error:"ACTION_INVALID"},400)}catch(e){const m=e.message||"SAFETY_ACTION_FAILED";const status=/LOGIN_REQUIRED/.test(m)?401:/ADMIN_REQUIRED/.test(m)?403:/INVALID|REQUIRED|ALREADY_OPEN|SELF_REPORT|DESCRIPTION/.test(m)?400:409;return json({error:m},status)}}